steps:
  abapEnvironmentCreateSystem:
    cfCredentialsId: 'CF_CREDENTIAL_EPAM'
    cfApiEndpoint: 'https://test.server.com'
    cfOrg: 'cfOrg'
    cfSpace: 'cfSpace'
    cfServiceInstance: 'H02_Q_system'
    cfService: 'abap'
    cfServicePlan: 'standard'
    abapSystemAdminEmail: 'epam.sap.poc.btp.trial.1@gmail.com'
    abapSystemDescription: 'ABAP Environment Q System'
    abapSystemIsDevelopmentAllowed: true
    abapSystemID: 'H02'
    abapSystemSizeOfPersistence: 4
    abapSystemSizeOfRuntime: 1 
