general:
steps:
    cloudFoundryCreateServiceKey:
        cfApiEndpoint: 'https://api.cf.eu10.hana.ondemand.com/'
        cfOrg: 'abapenv-tst-org'
        cfSpace: 'abap-dev'
        cfServiceInstance: 'abapenv-tst-inst'
        cfServiceKeyName: 'key'
        cfCredentialsId: 'CF_CREDENTIAL_EPAM'

