general:
steps:
  abapEnvironmentCreateSystem:
    cfCredentialsId: 'CF_CREDENTIALSID'
    cfApiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com/'
    cfOrg: '932f74detrial'
    cfSpace: 'dev'
    cfServiceInstance: 'H02_Q_system'
    cfService: 'ABAP environment'
    cfServicePlan: 'shared'
    abapSystemAdminEmail: 'sviatlana_isaichkina@epam.com'
    abapSystemDescription: 'ABAP Environment Q System'
    abapSystemIsDevelopmentAllowed: true
    abapSystemID: 'H02'
    abapSystemSizeOfPersistence: 4
    abapSystemSizeOfRuntime: 1 
