pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // Get code from a GitHub repository
                git url: 'https://github.com/isaichkina/subscribe_to_abap_pass', branch: 'main',
                 credentialsId: 'github_creds'
            }
        }
    }
}
